In [5]:
import pandas as pd
from datetime import datetime

In [6]:
data = pd.read_csv('/content/train.csv')

In [7]:
data.head()

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
0,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,NaN,12.50
1,2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,13 km/kg,1199 CC,88.7 bhp,5.0,8.61 Lakh,4.50
2,3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7.0,NaN,6.00
3,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.2 kmpl,1968 CC,140.8 bhp,5.0,NaN,17.74
4,6,Nissan Micra Diesel XV,Jaipur,2013,86999,Diesel,Manual,First,23.08 kmpl,1461 CC,63.1 bhp,5.0,NaN,3.50

# a)Handling missing values

In [8]:
missing_values = data.isnull().sum()

In [9]:
print("Missing values in each column:")

Missing values in each column:

In [10]:
print(missing_values)

Unnamed: 0              0
Name                    0
Location                0
Year                    0
Kilometers_Driven       0
Fuel_Type               0
Transmission            0
Owner_Type              0
Mileage                 2
Engine                 36
Power                  36
Seats                  38
New_Price            5032
Price                   0
dtype: int64

In [11]:
data.head()

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
0,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,NaN,12.50
1,2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,13 km/kg,1199 CC,88.7 bhp,5.0,8.61 Lakh,4.50
2,3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7.0,NaN,6.00
3,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.2 kmpl,1968 CC,140.8 bhp,5.0,NaN,17.74
4,6,Nissan Micra Diesel XV,Jaipur,2013,86999,Diesel,Manual,First,23.08 kmpl,1461 CC,63.1 bhp,5.0,NaN,3.50

#Replace with the Mean,mode,Median or drop them.

In [12]:
data['Mileage'] = data['Mileage'].str.replace(r'\D', '', regex=True)

In [13]:
data['Mileage'] = pd.to_numeric(data['Mileage'], errors='coerce')

In [14]:
data['Mileage'].fillna(data['Mileage'].mean(), inplace=True)

In [15]:
data['Engine'] = data['Engine'].str.replace(r'\D', '', regex=True)

In [16]:
data['Engine'] = pd.to_numeric(data['Engine'], errors='coerce')

In [17]:
data['Engine'].fillna(data['Engine'].mean(), inplace=True)

In [18]:
data['Power'] = data['Power'].str.replace(r'\D', '', regex=True)

In [19]:
data['Power'] = pd.to_numeric(data['Power'], errors='coerce')

In [20]:
data['Power'].fillna(data['Power'].mean(), inplace=True)

In [21]:
data['Seats'].fillna(data['Seats'].mean(), inplace=True)

In [22]:
data.drop(columns=['New_Price'], inplace=True)

In [23]:
updated_missing_values = data.isnull().sum()

In [24]:
print("\nUpdated missing values in each column:")

Updated missing values in each column:

In [25]:
print(updated_missing_values)

Unnamed: 0           0
Name                 0
Location             0
Year                 0
Kilometers_Driven    0
Fuel_Type            0
Transmission         0
Owner_Type           0
Mileage              0
Engine               0
Power                0
Seats                0
Price                0
dtype: int64

mileage, power, seats, engine
i)The columns "Mileage," "Power," "Seats," and "Engine" are fundamental attributes of a used car. These features are often essential for predicting a car's price, condition, and performance.
ii)Dropping these columns would reduce the dimensionality of your dataset
*These columns can also enhance the interpretability of your analysis
iii)New price
*High Missing Values
*Even if you were to impute missing values, the "New Price" data might not be of high quality or up-to-date, potentially introducing noise or inaccuracies into our analysis.

b) Removing Units , No need to clear already while doing mean, mode, median for the null values Units has been removed .PFB results

In [26]:
data.head()

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Price
0,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,1967.0,1582.0,1262.0,5.0,12.50
1,2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,13.0,1199.0,887.0,5.0,4.50
2,3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,2077.0,1248.0,8876.0,7.0,6.00
3,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,152.0,1968.0,1408.0,5.0,17.74
4,6,Nissan Micra Diesel XV,Jaipur,2013,86999,Diesel,Manual,First,2308.0,1461.0,631.0,5.0,3.50

C) Change the categorical variable

In [27]:
data = pd.get_dummies(data, columns=['Fuel_Type', 'Transmission'], drop_first=True)

In [28]:
data.head()

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Owner_Type,Mileage,Engine,Power,Seats,Price,Fuel_Type_Electric,Fuel_Type_Petrol,Transmission_Manual
0,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,First,1967.0,1582.0,1262.0,5.0,12.50,0,0,1
1,2,Honda Jazz V,Chennai,2011,46000,First,13.0,1199.0,887.0,5.0,4.50,0,1,1
2,3,Maruti Ertiga VDI,Chennai,2012,87000,First,2077.0,1248.0,8876.0,7.0,6.00,0,0,1
3,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Second,152.0,1968.0,1408.0,5.0,17.74,0,0,0
4,6,Nissan Micra Diesel XV,Jaipur,2013,86999,First,2308.0,1461.0,631.0,5.0,3.50,0,0,1

D) Create one more New Feature

In [29]:
current_year = datetime.now().year

In [30]:
data['Car_Age'] = current_year - data['Year']

In [31]:
data.head()

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Owner_Type,Mileage,Engine,Power,Seats,Price,Fuel_Type_Electric,Fuel_Type_Petrol,Transmission_Manual,Car_Age
0,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,First,1967.0,1582.0,1262.0,5.0,12.50,0,0,1,8
1,2,Honda Jazz V,Chennai,2011,46000,First,13.0,1199.0,887.0,5.0,4.50,0,1,1,12
2,3,Maruti Ertiga VDI,Chennai,2012,87000,First,2077.0,1248.0,8876.0,7.0,6.00,0,0,1,11
3,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Second,152.0,1968.0,1408.0,5.0,17.74,0,0,0,10
4,6,Nissan Micra Diesel XV,Jaipur,2013,86999,First,2308.0,1461.0,631.0,5.0,3.50,0,0,1,10

Store the processed dataset

In [32]:
data.to_csv('cleandataset_train.csv', index = False)